#!/bin/bash

LAST_TAG=$(git tag | sort -V | tail -1)
NEW_TAG=$(echo $LAST_TAG | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')

echo "New Tag: "$NEW_TAG

echo "__version__ = '$NEW_TAG'" > sdkcpc/__init__.py

BRANCH =$(git branch)

git add .
git commit -m "Last changes.Prepare __init__.py to release $NEW_TAG"
git push
git tag -a $NEW_TAG -m "New Release $NEW_TAG"
git push --tags





# value=`cat VERSION`
# build=$(date '+%Y/%m/%d %H:%M:%S')
# echo "- Last Version: $value"
# echo $value | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}' > VERSION
# value=`cat VERSION`
# echo "- New Version : $value"
# echo "__version__ = '$value'" > sdkcpc/__init__.py
# echo $build > sdkcpc/resources/software/BUILD
# echo $build > sdkcpc/BUILD
# echo "- Build       : $build"

# cp VERSION sdkcpc/resources/software

# pandoc README.md -o User_manual.pdf
rm -rf dist && python3 setup.py sdist
# # rm -rf dist
# # python3 setup.py sdist
# # twine upload --repository testpypi dist/*

# git add .
# git commit -m "compile and upload pytest version $value"
# git push origin develop