site_name: SDKCPC
site_url: https://destroyer-dcf.github.io/sdkcpc/
nav:
  - Inicio: 'index.md'
  - Acerca de: 'about.md'
  - Acerca de mi: 'about.md'
  - Acerca de ti: 'about.md'

theme: readthedocs

