site_name: SDKCPC
site_url: https://destroyer-dcf.github.io/sdkcpc/
repo_url: https://destroyer-dcf.github.io/sdkcpc/
repo_name: GitHub
site_author: Destroyer
site_description: Esto es una prueba de descripcion
copyright: Destroyer 2022
nav:
    - Introduction: 'index.md'
    - 'about.md'
    - 'Issue Tracker': 'https://example.com/'

version: 1.0.2
theme: readthedocs
  locale: es
  highlightjs: true
  logo: assets/about.png

