site_name: SDKCPC
site_url: https://destroyer-dcf.github.io/sdkcpc/
logo: img/about.png
nav:
  - Inicio: 'index.md'
  - Acerca de: 'about.md'
  - Acerca de mi: 'about.md'
  - Acerca de ti: 'about.md'

version: 1.0.2
theme: readthedocs

