# Project information
site_name: SDKCPC
site_url: https://github.com/destroyer-dcf/sdkcpc
site_author: Destroyer
copyright: © Copyright 2022, Destroyer. Revision 1.0.1
# Repository
repo_name: destroyer-dcf/sdkcpc
repo_url: https://github.com/destroyer-dcf/sdkcpc
edit_uri: ""

nav:
    - Inicio: 'index.md'
    - 'User Guide':
        - 'Instalación': 'instalation.md'
        - 'Comandos': 'commands.md'
        - 'Empezando': 'getting-started.md'
    - About:
        - 'Licencia': 'license.md'
        - 'Release Notes': 'release-notes.md'

theme:
  name: readthedocs
  include_sidebar: true
logo: assets/about.png
extra:
  version: latest
