#!/bin/bash

LAST_TAG=$(git tag | sort -V | tail -1)
NOTAS=$(cat NOTES)

echo "*******************************************"
echo "Create Pull Request $NEW_TAG to PYPI"
echo "*******************************************"
echo "[*] Tag   : "$LAST_TAG
echo "[*] Create pull request develop --> main"
gh pr create --title "Pull request Version $LAST_TAG" --body $NOTAS


